# Generated by Django 4.2.7 on 2023-11-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('short', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('1', 'For Rent'), ('2', 'For Sale'), ('3', 'Short-Let')], default='1', max_length=1)),
                ('type', models.CharField(choices=[('1', 'House'), ('2', 'Land'), ('3', 'commercial property'), ('4', 'Warehouses'), ('5', 'Fuel Stations')], default='1', max_length=1)),
                ('subtype', models.CharField(choices=[('1', 'Duplexes'), ('2', 'Block Of Flats'), ('3', 'Detached Duplexes'), ('4', 'Bungalow'), ('5', 'Mini Flats'), ('6', 'Semi detached Duplexes')], default='1', max_length=1)),
                ('bedroom', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '6+')], default='1', max_length=1)),
                ('toilet', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '6+')], default='1', max_length=1)),
                ('bathroom', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '6+')], default='1', max_length=1)),
                ('area', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('availability', models.CharField(default='', max_length=100)),
                ('totalarea', models.PositiveBigIntegerField(default=0)),
                ('coveredarea', models.PositiveBigIntegerField(default=0)),
                ('description', models.TextField(default=0, max_length=1000)),
                ('currencyfield', models.CharField(default=0, max_length=100)),
                ('url', models.URLField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumb', models.ImageField(null=True, upload_to='thumbnails/')),
                ('secondary', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_2', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_3', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_4', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_5', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_6', models.ImageField(null=True, upload_to='secondary_images/')),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
