# Generated by Django 5.2.2 on 2025-06-22 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('email', models.CharField(default=0, max_length=100)),
                ('phone', models.CharField(default=0, max_length=100)),
                ('asking', models.CharField(choices=[('Client', 'Client'), ('Agent', 'Agent')], default='Client', max_length=20)),
                ('house', models.CharField(choices=[('Duplexes', 'Duplexes'), ('Block Of Flats', 'Block Of Flats'), ('Detached Duplexes', 'Detached Duplexes'), ('Bungalow', 'Bungalow'), ('Mini Flats', 'Mini Flats'), ('Semi detached Duplexes', 'Semi detached Duplexes')], default='', max_length=30)),
                ('describe', models.TextField(default=0, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.IntegerField(help_text='Duration in Days')),
                ('post_limit', models.PositiveIntegerField(help_text='Number of posts allowed')),
                ('call_hours', models.PositiveIntegerField(help_text='Number of call hours allowed')),
                ('feature', models.CharField(max_length=100)),
                ('feature1', models.CharField(blank=True, max_length=100, null=True)),
                ('feature2', models.CharField(blank=True, max_length=100, null=True)),
                ('feature3', models.CharField(blank=True, max_length=100, null=True)),
                ('feature4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(default='', max_length=100)),
                ('short', models.CharField(default='', max_length=100)),
                ('category', models.CharField(choices=[('1', 'For Rent'), ('2', 'For Sale'), ('3', 'Short-Let')], default='1', max_length=1)),
                ('building', models.CharField(choices=[('1', 'House'), ('2', 'Land'), ('3', 'commercial property'), ('4', 'Warehouses'), ('5', 'Fuel Stations')], default='1', max_length=1)),
                ('subtype', models.CharField(blank=True, choices=[('1', 'Duplexes'), ('2', 'Block Of Flats'), ('3', 'Detached Duplexes'), ('4', 'Bungalow'), ('5', 'Mini Flats'), ('6', 'Semi detached Duplexes')], default='1', max_length=1, null=True)),
                ('bedroom', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '6+')], default='1', max_length=1, null=True)),
                ('toilet', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '6+')], default='1', max_length=1, null=True)),
                ('bathroom', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '6+')], default='1', max_length=1, null=True)),
                ('area', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('availability', models.CharField(default='', max_length=100)),
                ('totalarea', models.PositiveBigIntegerField(default=0)),
                ('coveredarea', models.PositiveBigIntegerField(default=0)),
                ('currencyfield', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default=0, max_length=1000)),
                ('url', models.URLField(default='')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumb', models.ImageField(null=True, upload_to='thumbnails/')),
                ('secondary', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_2', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_3', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_4', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_5', models.ImageField(null=True, upload_to='secondary_images/')),
                ('secondary_6', models.ImageField(null=True, upload_to='secondary_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100)),
                ('cname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('office', models.CharField(default=0, max_length=100)),
                ('phone', models.CharField(default=0, max_length=100)),
                ('email', models.CharField(default=0, max_length=100)),
                ('insta', models.CharField(default=0, max_length=100)),
                ('telegram', models.CharField(default=0, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, default='estateapp/image/apple.png', null=True, upload_to='profile/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid_active', models.BooleanField(default=False)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateapp.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
