# Generated by Django 4.2.7 on 2025-01-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=0, max_length=100)),
                ('cname', models.CharField(default=0, max_length=100)),
                ('username', models.CharField(default=0, max_length=100)),
                ('office', models.CharField(default=0, max_length=100)),
                ('phone', models.CharField(default=0, max_length=100)),
                ('email', models.CharField(default=0, max_length=100)),
                ('insta', models.CharField(default=0, max_length=100)),
                ('telegram', models.CharField(default=0, max_length=100)),
                ('profile', models.ImageField(null=True, upload_to='profile/')),
            ],
        ),
    ]
