# Generated by Django 5.2.2 on 2025-06-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='agent_verification/'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, null=True),
        ),
    ]
