# Generated by Django 5.2.2 on 2025-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_userplan_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='feature5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
