# Generated by Django 4.2.7 on 2025-01-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='street',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
