# Generated by Django 4.2.7 on 2025-01-31 19:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0003_rename_street_post_state_alter_profile_cname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currencyfield',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
