# Generated by Django 4.2.7 on 2025-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0004_alter_post_currencyfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currencyfield',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
