# Generated by Django 4.2.7 on 2025-02-26 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0005_alter_post_currencyfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='building',
        ),
    ]
