# Generated by Django 4.2.7 on 2025-02-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0006_rename_type_post_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currencyfield',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
