# Generated by Django 4.2.7 on 2025-03-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0007_alter_post_currencyfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
