# Generated by Django 4.2.7 on 2025-03-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0008_post_max_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='max_budget',
        ),
    ]
