# Generated by Django 4.2.7 on 2025-03-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0009_remove_post_max_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='currencyfield',
            field=models.CharField(default='', max_length=100),
        ),
    ]
