# Generated by Django 4.2.7 on 2025-03-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0011_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profile_picture',
        ),
    ]
