# Generated by Django 4.2.7 on 2025-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateapp', '0013_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='estateapp/image/apple.png', null=True, upload_to='profile/'),
        ),
    ]
