# Generated by Django 4.2.7 on 2025-03-31 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estateapp', '0014_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('post_limit', models.PositiveIntegerField(help_text='Number of posts allowed')),
                ('call_hours', models.PositiveIntegerField(help_text='Number of call hours allowed')),
                ('max_property_price', models.PositiveBigIntegerField(blank=True, help_text='Max property price allowed', null=True)),
                ('allowed_listings', models.TextField(help_text='Allowed listing types (e.g., Rent, Short-let, Sales)')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateapp.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
